# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Spotify.Spotify
PackageVersion: 1.2.38.720.ga4a70a0e
PackageLocale: en-US
Publisher: Spotify AB
PublisherUrl: https://www.spotify.com/
PublisherSupportUrl: https://support.spotify.com/
PrivacyUrl: https://www.spotify.com/legal/privacy-policy/
Author: Spotify Ltd
PackageName: Spotify
PackageUrl: https://www.spotify.com/download/
License: Proprietary
LicenseUrl: https://www.spotify.com/legal/
Copyright: Copyright (c) 2024, Spotify Ltd
ShortDescription: Spotify is a digital music service that gives you access to millions of songs.
Description: |-
  With Spotify, it’s easy to find the right music or podcast for every moment – on your phone, your computer, your tablet and more.

  There are millions of tracks and episodes on Spotify.  So whether you’re behind the wheel, working out, partying or relaxing, the right music or podcast is always at your fingertips.  Choose what you want to listen to, or let Spotify surprise you.

  You can also browse through the collections of friends, artists, and celebrities, or create a radio station and just sit back.

  Soundtrack your life with Spotify. Subscribe or listen for free.
Moniker: spotify
Tags:
- album
- artist
- audio
- episode
- music
- playlist
- podcast
- radio
- song
- sound
- streaming
PurchaseUrl: https://www.spotify.com/premium/
Documentations:
- DocumentLabel: About Us
  DocumentUrl: https://www.spotify.com/about-us/
ManifestType: defaultLocale
ManifestVersion: 1.6.0
